
package formularios;


import javax.swing.JOptionPane;

import Controller.ReclamoController;
import TableModel.ReclamoTableModel;
import javax.swing.JFrame;


public class ConsultarRegistroForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarRegistroForm.class.getName());
    
    /**
     * Creates new form ConsultarRegistroForm
     */
    public ConsultarRegistroForm() {
        initComponents();
        cargarTabla();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RegistroTable = new javax.swing.JTable();
        lbltext1 = new javax.swing.JLabel();
        lblRtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Registro", "Fecha Registro", "Tipo", "Desc", "Estado", "Canal Ingreso", "ID_Cliente", "ID_Area", "ID_Usuario Registro"
            }
        ));
        jScrollPane1.setViewportView(RegistroTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 350));

        lbltext1.setText("Total registros:");
        getContentPane().add(lbltext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblRtotal.setText("0");
        getContentPane().add(lblRtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarRegistroForm().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RegistroTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRtotal;
    private javax.swing.JLabel lbltext1;
    // End of variables declaration//GEN-END:variables
     
    ReclamoController obj = new ReclamoController();
    
    
    private void cargarTabla() {
    try {
        ReclamoTableModel model = obj.obtenerTablaReclamos() ;
        RegistroTable.setModel(model);
        lblRtotal.setText(model.getRowCount() + "");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
  
}
