/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author lenovo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemUsuario = new javax.swing.JMenuItem();
        itemArea = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemResolverReclamo = new javax.swing.JMenuItem();
        itemRegistrarReclamo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemSeguimientoReclamo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 204, 255));
        desktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        itemCerrarSesion.setText("Cerrar Sesión");
        jMenu1.add(itemCerrarSesion);

        itemSalir.setText("Salir");
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");

        itemCliente.setText("Clientes");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenu2.add(itemCliente);

        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(itemUsuario);

        itemArea.setText("Área");
        jMenu2.add(itemArea);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");

        itemResolverReclamo.setText("Resolver Reclamo");
        jMenu3.add(itemResolverReclamo);

        itemRegistrarReclamo.setText("Registrar Reclamo");
        itemRegistrarReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarReclamoActionPerformed(evt);
            }
        });
        jMenu3.add(itemRegistrarReclamo);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        itemSeguimientoReclamo.setText("Seguimiento");
        jMenu4.add(itemSeguimientoReclamo);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        itemReporte.setText("Reporte");
        jMenu5.add(itemReporte);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemRegistrarReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarReclamoActionPerformed
        // TODO add your handling code here:
        formRegistrarReclamo frm = new formRegistrarReclamo();
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }//GEN-LAST:event_itemRegistrarReclamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenuItem itemArea;
    public javax.swing.JMenuItem itemCerrarSesion;
    public javax.swing.JMenuItem itemCliente;
    public javax.swing.JMenuItem itemRegistrarReclamo;
    public javax.swing.JMenuItem itemReporte;
    public javax.swing.JMenuItem itemResolverReclamo;
    public javax.swing.JMenuItem itemSalir;
    public javax.swing.JMenuItem itemSeguimientoReclamo;
    public javax.swing.JMenuItem itemUsuario;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu5;
    public javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
